### ISSUE TITLE
MDNS Crash

### ISSUE THREAD

**Issue by scarca** [scarca/river#1]
MDNS Crashes on finding the chromecast. 

```
Callback: 
Error: getaddrinfo -3008
 at errnoException (/home/pi/serv/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
 at getaddrinfo_complete (/home/pi/serv/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
 at GetAddrInfoReqWrap.oncomplete (/home/pi/serv/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by scarca** [comment]
Fixed by using workaround from agnat/node_mdns#130 as provided by tberthe
